name: RSpec

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: gha
          POSTGRES_PASSWORD: gha
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options:
          --health-cmd "redis-cli --raw incr ping" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      FORBID_FOCUSED_SPECS: 1
      RAILS_ENV: test
      POSTGRES_USER: gha
      POSTGRES_PASSWORD: gha

    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: sudo apt install libpq-dev libvips tesseract-ocr tesseract-ocr-eng libpoppler-dev poppler-utils

      - name: Setup database
        run: |
          cp config/database.gha.yml config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Run migrations
        run: bin/rails db:migrate

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Run RSpec
        run: bundle exec rspec

      - name: Add code coverage comment
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: coverage/lcov/kouress.lcov
