name: RSpec

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      FORBID_FOCUSED_SPECS: 1

    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Run migrations
        run: bin/rails db:migrate RAILS_ENV=test

      - name: Run RSpec
        run: bundle exec rspec
