name: RuboCop

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: gha
          POSTGRES_PASSWORD: gha
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        healthcheck:
          test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
          interval: 10s
          timout: 5s
          retries: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install libraries
        run: sudo apt install libpq-dev

      - name: Setup database
        run: |
          cp config/database.gha.yml config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: gha
          POSTGRES_PASSWORD: gha

      - name: Run migrations
        run: bin/rails db:migrate
        env:
          RAILS_ENV: test
          POSTGRES_USER: gha
          POSTGRES_PASSWORD: gha

      - name: Precompile assets
        run: rails assets:precompile
        env:
          RAILS_ENV: test
          POSTGRES_USER: gha
          POSTGRES_PASSWORD: gha

      - name: Run RuboCop
        run: bundle exec rubocop --config .rubocop.yml --parallel
        env:
          RAILS_ENV: test
          POSTGRES_USER: gha
          POSTGRES_PASSWORD: gha
